language: node_js
node_js:
- stable
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "bw-faq"
env:
  global:
  - ENCRYPTION_LABEL: bec02c3e0753
  - COMMIT_AUTHOR_EMAIL: dtolbert@bandwidth.com
  - secure: HwXkYdXPnjquXUGmDGza4iP2IbB/vgDzlMLYmBZMoEmYdPPxFAOYRFPIWFBpBSNHT0Awfgj80bFV7g2C8qe5iukx76SZpcwBVNYxLwpa2B25ywBR/OQNTJFDWzOSgJQn04hZgRdSgr9XJ0YYmydSR3r+PrbBlUqGpFIBRFC/gYeUWwvEKrOUIZgfeZraqGhlPGyUEHx0qf3X4476SMH8e8mYxmZ6m9BbvR/wJnR6Rtdov0l5TH8hOTBE7fizbPEiz8D6EHDTJd+7SV5ab4tPsEbErUfU6XE5izyJaIKTH9O7kJzdurgFbiEi8B/e7J17mP9DALLsGr6TPcYupFdao/+TPetU0lxHUsvPT8UbXmHx2Fjy9uVFkyZu6GQ2D8c5eEIGTcslu7GZQvoUYmgf01pO3u1K50FWuCcZ78juQOAKvDyUtP6MqcoD95NNZgn1Tw7CICJMVO+ecnKKgZJRNelcgFnizSLTHCl+g0OigTjgNiVZl+jm862PwkiZZtozTlp/nPNOaEW1OwbZqS78v+bifyLlR2Zec/zW+VJ3uwLKP5QOhk5Fimwr4v3aG2VeugefYvThFGlyEyTFKskSqaeXNnHcdKafCPI+VzMXYnM6AbRvw6H+W+sZIC3KaC+pIY7Lui/GTjshuljey+UJG/G7xA0SKU3OiHWDeDA1190=
  - secure: EwqNKHif5T7Sw5oIU3Fht83AOQQouQGcevaFkbql1JZ8XvHeLLT8QQdHedpR/UAAFwN4tfmYFbpC85Gv7FgncFqELwkHQLmytl9WbhVvXIiNhVRvKPxe8D/QxCs8YUWYf/AAVhox5NTKDOv1eyJwK7dwTHhPDU6uS/cbbmF1OXVNMHXHbEcK/G/nuDBcTLgoRlkdXA3LLnoLHfdlELCEwm1q+LvHPt8MxC+Dguuaj1jmzJ9YnBqj71l7wCdHBc0i/XaPSPWCsNfuSxLxJhEMrrBX3HmlDGaOvJawWm1SvJZrNXlnL5luXX1rNwCOzRNM4/8hz/pxgqq49jVCw9/4EUJJgoKDd6kpg/DXWl5wZWVmyffyVNLfrX20OOO68Voy/NvlT+33GrO8vbUX1R5Q1j/FAqtWvcogxVUmMtZ4Gi+DfWyj7KkE5YWny6pdHrBTOdQKSimN77Q9VQyPhentz+4qm1eq9EjewCCyiTYSfbdfKZBiRhSUhDVPYZNu+8vct/6zAEF5rYbcFutFwCCldQ8KHPZnyvKJzNWBsgsZUuhg/8Do20ZTxaVxP19GSogRsWNco0brUPS2pjWB22OIfUXrXcdI4KeQuL5admV5+RmvPxVGr8szQBsnD09GjelpzZnXg0xCZH8g34Ub+JM+zT6wT0LW+243iQB3XuTr7Ow=
  - secure: mMASwitRQ9VEmJtxXznBwD/oL6XZ55I5bjR5bD/VYE4tzU9S8KC6uzyQQoMfGGIgYDlOciWSOIdzIb1EkywCQ/ueBFODMz9wFGNnGM5QsJu9OWtpQkGRQbaWsIUB6qi1f5XY7ZUiCx5IkbELynJbJa2WNGqpJy2u+z7y0oucxwI293vB8oCte48l2x+WbdRlzGxAoYuPm9NhWJkwfvYtcClOerB6GcL8xPRxou2Z9F+fioo15UbpG+Spb/qiXzw0/CS3/sYB7y4WRPsp1SuqMW74KDwJu9K1FhrSttL5huh+VTailnI0EEN5EYwlZXpYrSiVutLoV8xBnO4oIjGlj3M/U+GFVM9+JUkdenXL6OvDSF3JDkxnHXlr7MnybpvUdV+JTh3BQhM6wE50rCmkV7tZrBO90flbtMOdin33tVMmAaoFsFTu2UiQ2nbCfjFvm4EH+NaLE387fcqPwdjcy93a8AcftmZuLyY4xEse8Olitp9YKA4zh9BlBj1abDQjB3S05D3phLYw+QV2yInEz4Oala8iuMaBiucFuAxSR8rSlGjRlZ7t/Q1OkOM0M9x1WM3+SczUfJOMEepeBWymVYmQeHqDeKRgIsDYFMaPABHZ4EB31V0K4S3BzfIX+l1rBFi713XbOwx/dOvbje5juPzdtO+oUQepCjidgpaAn88=
