language: node_js
node_js:
- stable
before_install:
- sudo pip install virtualenv
- virtualenv my_project
- source my_project/bin/activate
before_script:
- npm install -g gitbook-cli
script: bash ./deploy.sh
after_success:
- rm -rf _book/my_project
- pip install git+https://github.com/dtolb/s3-deploy-website.git
- s3-deploy-website "bw-faq"
env:
  global:
  - ENCRYPTION_LABEL: bec02c3e0753
  - COMMIT_AUTHOR_EMAIL: developerhelp@bandwidth.com
  - secure: m3QoWqlfcO6Dkrtop02dfEFVGmKva47iaM6uULo22iiB/4XfjdaKmg1DYK505jNTt7wFbrf3ZgerS/yVsHWnhXhER7MLcYBfJgk5r/n/2jzG+0SEOSE+0kqYQDxmjw3REpAkZ25WYzMIwqX/88zE6FBHby7xWB4yPWY3+9NkQMZF2rSMuizFPYxI8azoQrxm/Fqek3+y30Rp27HxIcBprgV9tufS0fmj1GvC4GRJJ0cVU8QgS9zbOInYUsIDt78LZNMJwEbiRMQxAkhw8QvaLJrEh2466kVAKGbjmVw3ymWfEWeh/0arfu2ssebaTZpjofUGyOrb3UN1N3akabyE4SFZmSeYJLr3Slt58QpC5ZdI6XOmGEJGeM1mOwLvyAUJ3OXp3yKg61k1eYzovF/TWVJfs9RNZOZ5+E1/9tZH/zkhEFfGWMfxUc7pUD5b89Fj5l44WJyclP8VfxKnHhdMU8EnfcNO4NMlsJiBjdCaLhX36bsTsXz4enq4BDmFd1iywX84ZmcXixr1G18WBRzGbut/oiTDS0e5y8FAB0Q93j2E7x1YPbxUNTQK+gKQ40wnWnOpgqHT7vA9eWprJ7l77Okz5hhgF2JirrtETYkc4pcwbuMjz3VZY4uhzEwHhvc1rNBUwoV18Mhb70rLPADwDMnAXLa5jvWvwMSojFrJtvU=
  - secure: MlRmQAHnQbZCqXZobP7Hgi30joDExKwDCxDh7a0E25ZbGkQgNrrkAqCMhL0o+21MiQuKB5MWquxuSsy9qYKFqJtnkxh0SgZ160zTaUankvWLKFcJBkmIwUjNoYYQt06ibGaFm1mHVEl0aO85Z9RqihWaCBt3IbQ0Q8/0+R3hgEZxi6vRzstqscYjz8K7guo0IpU41nZMa/r1MV2RlWjmIiNLJvndT2wZZ/F0YMgiITs4RmnGJXQw4xgCeoB/WLbmvBTkptYBje7Sdqv4NL6Zdz7gKSApeJ0lpG8cXr2V5TrL/hp4307LXm9VkqXo+oCNA/nzLg+BTG1OwBOaVF+HStkKSWmtcnHVdHtM3WhxiwZZHXOra8fwn8iw8/fJE5UTLVE5SIvbm74BWYO19YamG7F4A1h06BWUZxzlI5/kYNBAA4YZZ9CYRjZsVP83Sl4MfpCPKsVwzS14bOlvEW5RcM9NO5Fw1DBAqvXa58QWtIvg1tlJVOrJF/fpSoJ/lCoNQ+aOn9uZMCX9OKZ4q0oqjpeOEne0rTceS123UAdR9R+JtEGZNRsQVo1oaPO2eJxJc2IGuEM+70W3oNgIHjGRv8gjGc6iNOol2Dsd6cvmg08abd+EN3x+cBptfEeZnYz1G8yZrLm5Qmp5RNN8Qvr5qe8GP2AMCW4mrXQKTO2ISvo=
  - secure: JwfeBVbQH/1y6F/RRq2JfxkoAUZFANvo2LgoJKZ2HcxMDxQ0OMC3JD7FVv9HDacCSbngmRljOKo24uh5feHPK7/wJI4JdV3PLy9pnjlOF0hM2zX+1yM8HWbFRAhxBoJQd7lYweuPmMSLwpl5GkkjI2kQ7un4GeBFyistBTnpe9NR0gdd+OyOW7cxZfpRGe2jIX8vEpw92GP62Jt5DJ+fyhDhU6SNaFwruluCUFXjMQt6v+MgZG4Ovi+4551LJMd3bMgAjfAtiSc5EJnFEMUDpKqx4VPc8SGXq1iF1uUI8hpRzvEt5AYz3+PhbH3tdNARnrl96xE5DNKmun30rL3ehBp4wN079m8mj9sAeODA1sM5//572ICAyRt4tkMILbG3ONp7sEdUVEhaAMy2hZE60COo/1bvZrLopbUCZJpFRb1rA/FLn4xkW4uHXXVZLg6YS9rweGUd3El6AUEXgwlnw4y/60Nwts9Sk+bUa+AuXfm89BZWlFgXHcjcf86uvG36FsAAExsmav/e757pKdvN/0orXl5qd004kK1MjCf0P/Nw6lqx1lwJ/+H+Kw910w9VAcOL+eDw2IUp89QUG8QOIofBrmto5m3rQlWdx8URxumResVwEbqqnquS/c2u6KXe8kdq8Q0ugOYFyKBD9MswkDmzxscpZ3ujqIJLDZFDWYI=
